In [2]:
# Import Libirary
import pandas as pd

In [3]:
# Creating Series Using Pandas
marks = pd.Series([85,96,87],index=['Rahul','Amit','Priya'])
print(marks)

Rahul    85
Amit     96
Priya    87
dtype: int64

In [4]:
# Acces the Specifiic Value
print(marks['Rahul'])

85

In [5]:
# A DataFrame is a two-dimensional table with rows and columns
data = {
    "Name": ["Rahul", "Amit", "Priya"],
    "Age": [20, 21, 22],
    "Marks": [85, 72, 95]
}
df = pd.DataFrame(data)
print(df)

# View First 5 Element
print("\nFirst 5 Elemnt is:\n",df.head(2))

# View Last 5 Rows
print("\nLast Element is:\n",df.tail())

# View Shape of Data
print("\n Shape of Dataset is:",df.shape)

# View Columns in the Data DataSet
print("\n Columns in Dataset:",df.columns)

# Info Of dataset
print("\nInfo Of Data Set:",df.info)

# Describe of Data
print("\nDesribe of Dataset:",df.describe)

# Dtypes Of Dataset
print("\nDatatypes of Data:",df.dtypes)

    Name  Age  Marks
0  Rahul   20     85
1   Amit   21     72
2  Priya   22     95

First 5 Elemnt is:
     Name  Age  Marks
0  Rahul   20     85
1   Amit   21     72

Last Element is:
     Name  Age  Marks
0  Rahul   20     85
1   Amit   21     72
2  Priya   22     95

 Shape of Dataset is: (3, 3)

 Columns in Dataset: Index(['Name', 'Age', 'Marks'], dtype='object')

Info Of Data Set: <bound method DataFrame.info of     Name  Age  Marks
0  Rahul   20     85
1   Amit   21     72
2  Priya   22     95>

Desribe of Dataset: <bound method NDFrame.describe of     Name  Age  Marks
0  Rahul   20     85
1   Amit   21     72
2  Priya   22     95>

Datatypes of Data: Name     object
Age       int64
Marks     int64
dtype: object

In [6]:
# Access the Columns
df['Name']
df[["Name", "Marks"]]

    Name  Marks
0  Rahul     85
1   Amit     72
2  Priya     95

In [7]:
#Selecting Rows
df.loc[0]
# Multiple rows
df.loc[0:2]

    Name  Age  Marks
0  Rahul   20     85
1   Amit   21     72
2  Priya   22     95

In [8]:
# Acces The MArks Which is Greater than 80
df[df["Marks"] > 80]

    Name  Age  Marks
0  Rahul   20     85
2  Priya   22     95

In [9]:
# Age greater than or equal to 21
df[df['Age']>= 21]

    Name  Age  Marks
1   Amit   21     72
2  Priya   22     95

In [10]:
# Age greater than 21 and marks greater than 80
df[(df['Marks']>80) & (df['Age']>=21)]

    Name  Age  Marks
2  Priya   22     95

In [11]:
#Adding a New Column
df["Grade"] = ['A','B','C']
df.head()

    Name  Age  Marks Grade
0  Rahul   20     85     A
1   Amit   21     72     B
2  Priya   22     95     C

In [12]:
#Create a calculated column
df['Bonus Marks'] = df['Marks'] + 1
df.head()

    Name  Age  Marks Grade  Bonus Marks
0  Rahul   20     85     A           86
1   Amit   21     72     B           73
2  Priya   22     95     C           96

In [13]:
# Deleting Columns
df = df.drop("Age", axis=1)
df.head()

    Name  Marks Grade  Bonus Marks
0  Rahul     85     A           86
1   Amit     72     B           73
2  Priya     95     C           96

In [14]:
#Check missing values
df.isnull()

# Check missing values Count
df.isnull().sum()

# Remove missing values
df.dropna()

    Name  Marks Grade  Bonus Marks
0  Rahul     85     A           86
1   Amit     72     B           73
2  Priya     95     C           96

In [15]:
#Fill with mean Missing Value
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

In [16]:
#Sorting Data
df.sort_values("Marks", ascending=False)

    Name  Marks Grade  Bonus Marks
2  Priya     95     C           96
0  Rahul     85     A           86
1   Amit     72     B           73

In [17]:
#Value Counts
df['Grade'].value_counts()

Grade
A    1
B    1
C    1
Name: count, dtype: int64

In [18]:
data = {
    "Department": ["IT", "HR", "IT", "HR", "Sales"],
    "Salary": [50000, 40000, 60000, 45000, 55000]
}

df = pd.DataFrame(data)

In [19]:
#Average salary by department
df.groupby("Department")["Salary"].mean()

Department
HR       42500.0
IT       55000.0
Sales    55000.0
Name: Salary, dtype: float64

In [20]:
# Find Total Salary Departmentwise
df.groupby("Department")['Salary'].sum()

Department
HR        85000
IT       110000
Sales     55000
Name: Salary, dtype: int64

In [21]:
# Find the Maximum Salary Department Wise
df.groupby("Department")["Salary"].max()

Department
HR       45000
IT       60000
Sales    55000
Name: Salary, dtype: int64

Practice Question

In [22]:
# Question 1
"""


data = {
    "Name": ["Rahul", "Priya", "Amit", "Sneha", "Rohan", "Priya"],
    "Department": ["IT", "HR", "IT", "Sales", "HR", "HR"],
    "Age": [25, 28, 30, np.nan, 32, 28],
    "Salary": [50000, 45000, 60000, 55000, np.nan, 45000]
}
1.Display the first 3 rows.
2.Check the shape and data types.
3.Find missing values.
4.Fill missing Age with the average age.
5.Fill missing Salary with the average salary.
6.Find duplicate rows and remove them.
7.Display employees earning more than 50,000.
8.Add a Bonus column equal to 10% of Salary.
9.Sort employees by Salary in descending order.
10.Find the average salary of each department.
"""

import numpy as np
import pandas as pd

data = {
    "Name": ["Rahul", "Priya", "Amit", "Sneha", "Rohan", "Priya"],
    "Department": ["IT", "HR", "IT", "Sales", "HR", "HR"],
    "Age": [25, 28, 30, np.nan, 32, 28],
    "Salary": [50000, 45000, 60000, 55000, np.nan, 45000]
}

df = pd.DataFrame(data)

#1.Display the first 3 rows.
df.head(5)

    Name Department   Age   Salary
0  Rahul         IT  25.0  50000.0
1  Priya         HR  28.0  45000.0
2   Amit         IT  30.0  60000.0
3  Sneha      Sales   NaN  55000.0
4  Rohan         HR  32.0      NaN

In [23]:
#2.Check the shape and data types
df.shape
df.dtypes

Name           object
Department     object
Age           float64
Salary        float64
dtype: object

In [24]:
#3.Find missing values
df.isnull()
df.isnull().sum()

Name          0
Department    0
Age           1
Salary        1
dtype: int64

In [25]:
#4.Fill missing Age with the average age.
df['Age'] = df['Age'].fillna(df['Age'].mean())
df.isnull().sum()

Name          0
Department    0
Age           0
Salary        1
dtype: int64

In [26]:
#5..Fill missing Salary with the average Salary.
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df.isnull().sum()

Name          0
Department    0
Age           0
Salary        0
dtype: int64

In [27]:
#6.Find duplicate rows and remove them.
df.duplicated()
df.drop_duplicates()

    Name Department   Age   Salary
0  Rahul         IT  25.0  50000.0
1  Priya         HR  28.0  45000.0
2   Amit         IT  30.0  60000.0
3  Sneha      Sales  28.6  55000.0
4  Rohan         HR  32.0  51000.0

In [28]:
#7.Display employees earning more than 50,000.
df[df['Salary']> 50000]

    Name Department   Age   Salary
2   Amit         IT  30.0  60000.0
3  Sneha      Sales  28.6  55000.0
4  Rohan         HR  32.0  51000.0

In [29]:
#8.Add a Bonus column equal to 10% of Salary.
df['Bonus'] = df['Salary']*0.1
df.head()

    Name Department   Age   Salary   Bonus
0  Rahul         IT  25.0  50000.0  5000.0
1  Priya         HR  28.0  45000.0  4500.0
2   Amit         IT  30.0  60000.0  6000.0
3  Sneha      Sales  28.6  55000.0  5500.0
4  Rohan         HR  32.0  51000.0  5100.0

In [30]:
#9.Sort employees by Salary in descending order.
df.sort_values("Salary",ascending=False)

    Name Department   Age   Salary   Bonus
2   Amit         IT  30.0  60000.0  6000.0
3  Sneha      Sales  28.6  55000.0  5500.0
4  Rohan         HR  32.0  51000.0  5100.0
0  Rahul         IT  25.0  50000.0  5000.0
1  Priya         HR  28.0  45000.0  4500.0
5  Priya         HR  28.0  45000.0  4500.0

In [31]:
#10.Find the average salary of each department.
df.groupby("Department")['Salary'].mean()

Department
HR       47000.0
IT       55000.0
Sales    55000.0
Name: Salary, dtype: float64

In [33]:
# Question 2
"""
data = {
    "Product": ["Laptop", "Mobile", "Laptop", "Headphones", "Mobile", "Laptop"],
    "Category": ["Electronics", "Electronics", "Electronics",
                 "Accessories", "Electronics", "Electronics"],
    "City": ["Nagpur", "Pune", "Nagpur", "Mumbai", "Pune", "Mumbai"],
    "Quantity": [2, 5, 3, 10, 4, 1],
    "Price": [50000, 20000, 50000, 2000, 20000, 50000]
}

1.Add a Total_Sales column
2.Find total sales of the entire store.
3.Find products with Quantity > 3.
4.Sort products by Total_Sales in descending order.
5.Find total sales by City
6.Find total sales by Product
7.Find the city with the highest total sales.
8.Use value_counts() to count how many times each product appears.
"""

data = {
    "Product": ["Laptop", "Mobile", "Laptop", "Headphones", "Mobile", "Laptop"],
    "Category": ["Electronics", "Electronics", "Electronics",
                 "Accessories", "Electronics", "Electronics"],
    "City": ["Nagpur", "Pune", "Nagpur", "Mumbai", "Pune", "Mumbai"],
    "Quantity": [2, 5, 3, 10, 4, 1],
    "Price": [50000, 20000, 50000, 2000, 20000, 50000]
}

df = pd.DataFrame(data)

#1.Add a Total_Sales column
df['Total_Sales'] = df['Quantity']*df['Price']
df.head()

      Product     Category    City  Quantity  Price  Total_Sales
0      Laptop  Electronics  Nagpur         2  50000       100000
1      Mobile  Electronics    Pune         5  20000       100000
2      Laptop  Electronics  Nagpur         3  50000       150000
3  Headphones  Accessories  Mumbai        10   2000        20000
4      Mobile  Electronics    Pune         4  20000        80000

In [35]:
#2.Find total sales of the entire store.
print("Total Sales(Rs):",df['Total_Sales'].sum())

Total Sales(Rs): 500000

In [36]:
#3.Find products with Quantity > 3.
df[df['Quantity']>3]

      Product     Category    City  Quantity  Price  Total_Sales
1      Mobile  Electronics    Pune         5  20000       100000
3  Headphones  Accessories  Mumbai        10   2000        20000
4      Mobile  Electronics    Pune         4  20000        80000

In [37]:
#4.Sort products by Total_Sales in descending order.
df.sort_values("Total_Sales",ascending=False)

      Product     Category    City  Quantity  Price  Total_Sales
2      Laptop  Electronics  Nagpur         3  50000       150000
0      Laptop  Electronics  Nagpur         2  50000       100000
1      Mobile  Electronics    Pune         5  20000       100000
4      Mobile  Electronics    Pune         4  20000        80000
5      Laptop  Electronics  Mumbai         1  50000        50000
3  Headphones  Accessories  Mumbai        10   2000        20000

In [38]:
#5.Find total sales by City
df.groupby("City")['Total_Sales'].sum()

City
Mumbai     70000
Nagpur    250000
Pune      180000
Name: Total_Sales, dtype: int64

In [39]:
#6.Find total sales by Product
df.groupby("Product")['Total_Sales'].sum()

Product
Headphones     20000
Laptop        300000
Mobile        180000
Name: Total_Sales, dtype: int64

In [41]:
#7.Find the city with the highest total sales.
df.groupby("City")['Total_Sales'].sum().idxmax()

'Nagpur'

In [42]:
#8.Use value_counts() to count how many times each product appears.
df['Product'].value_counts()

Product
Laptop        3
Mobile        2
Headphones    1
Name: count, dtype: int64

In [43]:
import pandas as pd
import numpy as np

data = {
    "Patient_ID": [101, 102, 103, 104, 105, 106, 107, 108],

    "Name": [
        "Rahul", "Priya", "Amit", "Sneha",
        "Rohan", "Pooja", "Amit", "Kiran"
    ],

    "Department": [
        "Cardiology", "Neurology", "Cardiology", "Orthopedic",
        "Neurology", "Cardiology", "Cardiology", "Orthopedic"
    ],

    "Age": [45, 32, 50, np.nan, 28, 60, 50, 40],

    "Days_Admitted": [5, 3, 7, 4, np.nan, 6, 7, 2],

    "Treatment_Cost": [
        50000, 35000, 80000, 45000,
        30000, np.nan, 80000, 25000
    ]
}

df = pd.DataFrame(data)

df.head()

   Patient_ID   Name  Department   Age  Days_Admitted  Treatment_Cost
0         101  Rahul  Cardiology  45.0            5.0         50000.0
1         102  Priya   Neurology  32.0            3.0         35000.0
2         103   Amit  Cardiology  50.0            7.0         80000.0
3         104  Sneha  Orthopedic   NaN            4.0         45000.0
4         105  Rohan   Neurology  28.0            NaN         30000.0

In [44]:
df.shape

(8, 6)

In [45]:
df.columns

Index(['Patient_ID', 'Name', 'Department', 'Age', 'Days_Admitted',
       'Treatment_Cost'],
      dtype='object')

In [46]:
df.dtypes

Patient_ID          int64
Name               object
Department         object
Age               float64
Days_Admitted     float64
Treatment_Cost    float64
dtype: object

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient_ID      8 non-null      int64
 1   Name            8 non-null      object
 2   Department      8 non-null      object
 3   Age             7 non-null      float64
 4   Days_Admitted   7 non-null      float64
 5   Treatment_Cost  7 non-null      float64
dtypes: float64(3), int64(1), object(2)
memory usage: 516.0+ bytes

In [48]:
df.describe()

       Patient_ID        Age  Days_Admitted  Treatment_Cost
count     8.00000   7.000000       7.000000        7.000000
mean    104.50000  43.571429       4.857143    49285.714286
std       2.44949  11.133390       1.951800    22625.312416
min     101.00000  28.000000       2.000000    25000.000000
25%     102.75000  36.000000       3.500000    32500.000000
50%     104.50000  45.000000       5.000000    45000.000000
75%     106.25000  50.000000       6.500000    65000.000000
max     108.00000  60.000000       7.000000    80000.000000

In [50]:
df.isnull()
df.isnull().sum()

Patient_ID        0
Name              0
Department        0
Age               1
Days_Admitted     1
Treatment_Cost    1
dtype: int64

In [54]:
df["Age"] = df['Age'].fillna(df['Age'].mean())
df['Days_Admitted'] = df['Days_Admitted'].fillna(df['Days_Admitted'].mean())
df['Treatment_Cost'] = df['Treatment_Cost'].fillna(df['Treatment_Cost'].mean())
df.isnull().sum()

Patient_ID        0
Name              0
Department        0
Age               0
Days_Admitted     0
Treatment_Cost    0
dtype: int64

In [57]:
df.duplicated()
df.duplicated().sum()
df.drop_duplicates()

   Patient_ID   Name  Department        Age  Days_Admitted  Treatment_Cost
0         101  Rahul  Cardiology  45.000000       5.000000    50000.000000
1         102  Priya   Neurology  32.000000       3.000000    35000.000000
2         103   Amit  Cardiology  50.000000       7.000000    80000.000000
3         104  Sneha  Orthopedic  43.571429       4.000000    45000.000000
4         105  Rohan   Neurology  28.000000       4.857143    30000.000000
5         106  Pooja  Cardiology  60.000000       6.000000    49285.714286
6         107   Amit  Cardiology  50.000000       7.000000    80000.000000
7         108  Kiran  Orthopedic  40.000000       2.000000    25000.000000

In [60]:
#Find patients older than 40 years.
df[df['Age']>40]

   Patient_ID   Name  Department        Age  Days_Admitted  Treatment_Cost
0         101  Rahul  Cardiology  45.000000            5.0    50000.000000
2         103   Amit  Cardiology  50.000000            7.0    80000.000000
3         104  Sneha  Orthopedic  43.571429            4.0    45000.000000
5         106  Pooja  Cardiology  60.000000            6.0    49285.714286
6         107   Amit  Cardiology  50.000000            7.0    80000.000000

In [61]:
#Find patients whose treatment cost is greater than ₹40,000
df[df['Treatment_Cost']>40000]

   Patient_ID   Name  Department        Age  Days_Admitted  Treatment_Cost
0         101  Rahul  Cardiology  45.000000            5.0    50000.000000
2         103   Amit  Cardiology  50.000000            7.0    80000.000000
3         104  Sneha  Orthopedic  43.571429            4.0    45000.000000
5         106  Pooja  Cardiology  60.000000            6.0    49285.714286
6         107   Amit  Cardiology  50.000000            7.0    80000.000000

In [70]:
df[["Name", "Department", "Treatment_Cost"]]

    Name  Department  Treatment_Cost
0  Rahul  Cardiology    50000.000000
1  Priya   Neurology    35000.000000
2   Amit  Cardiology    80000.000000
3  Sneha  Orthopedic    45000.000000
4  Rohan   Neurology    30000.000000
5  Pooja  Cardiology    49285.714286
6   Amit  Cardiology    80000.000000
7  Kiran  Orthopedic    25000.000000

In [72]:
#Find the highest treatment cost.
df['Treatment_Cost'].max()

80000.0

In [73]:
df.groupby("Department")['Treatment_Cost'].mean()

Department
Cardiology    64821.428571
Neurology     32500.000000
Orthopedic    35000.000000
Name: Treatment_Cost, dtype: float64

In [74]:
df.sort_values("Treatment_Cost",ascending=False)

   Patient_ID   Name  Department        Age  Days_Admitted  Treatment_Cost
2         103   Amit  Cardiology  50.000000       7.000000    80000.000000
6         107   Amit  Cardiology  50.000000       7.000000    80000.000000
0         101  Rahul  Cardiology  45.000000       5.000000    50000.000000
5         106  Pooja  Cardiology  60.000000       6.000000    49285.714286
3         104  Sneha  Orthopedic  43.571429       4.000000    45000.000000
1         102  Priya   Neurology  32.000000       3.000000    35000.000000
4         105  Rohan   Neurology  28.000000       4.857143    30000.000000
7         108  Kiran  Orthopedic  40.000000       2.000000    25000.000000